name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this matches your default branch (main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project (optional, for frameworks like React, Vue)
      run: |
        npm install
        npm run build  # If you're using a build tool

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Or the directory where your website files are
 
